### ISSUE TITLE
Translated texts are not in the right order.

### ISSUE THREAD

**Issue by YomostXme** [DCY1117/MangaQuick#2]
After some tests, it seems that there is something wrong with the texts placement.

Original image:
![34 (1)](https://github.com/DCY1117/MangaQuick/assets/107755697/db1a5a11-46e2-4a1a-8773-0866410457fd)

This is the result after i using MangaQuick:

![23](https://github.com/DCY1117/MangaQuick/assets/107755697/ee90fd49-2798-40c0-b820-7825581b46f3)

Compare it to the result from [cotrans](https://cotrans.touhou.ai/):

![34 (1) jpg](https://github.com/DCY1117/MangaQuick/assets/107755697/efcbc85c-a681-449d-bf87-b27e349ed024)

As you can see the translation is almost the same, but the texts are placed in the wrong order.

**Comment by DCY1117** [comment]
Yep, true. Thanks for pointing this out. I'll check into the translation order issue and see what's going on.

**Comment by DCY1117** [comment]
It should work now.
I changed it, so the blocks are detected again after modifying the masks.

Was the installation process hard?
Also, the cotrans app is way better in terms of translation and detection. If you have any ideas of improvements, I'm open to hearing them.

This is a piece of work I completed in 2022. Since then, there have been significant advancements in text detection, OCR, and inpainting. I didn't upload the code at the time, but I've decided to share it now (why not). However, the original code was poorly written, so I've attempted to reorganize it and make it more modular. This is the revised version.

**Comment by DCY1117** [comment]
Result after using MangaQuick:
![310724104-db1a5a11-46e2-4a1a-8773-0866410457fd](https://github.com/DCY1117/MangaQuick/assets/109959299/97941103-f25a-4fd2-a405-f7c35af07797)

**Comment by YomostXme** [comment]
Thanks for fixing the problems. Now the application works flawlessly. Of course, it's simple to follow the installation process
Also the cotrans app is based from [manga-image-translator](https://github.com/zyddnys/manga-image-translator) and [ballonstranslator](https://github.com/dmMaze/BallonsTranslator). If you want to improve your code, you can base it on these open-source projects.
Here are some improvements I can think of:
- better text segmentation
- add more free text translations and separate them in each class
- Improve text resize algorithm, some texts are too small/big
- Detection of text color
